# This is a basic workflow to help you get started with Actions
name: DeployToAWS
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  packer_build:
    name: workflow_aws
    runs-on: ubuntu-latest
    outputs:
      ID_OF_AMI: ${{steps.AMI_ID_OUTPUT.outputs.ID_OF_AMI}}

    strategy:
      matrix:
        node-version: [18.x]


    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1.0.0
      - name: Run packer commands
        run: |
          zip -r webApp.zip ./
          pwd ./webApp
          packer build  -var-file="vars.json" ami.json.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}          
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Getting AMI id as outputs
        id: AMI_ID_OUTPUT
        run: |
          ID_OF_AMI=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo $ID_OF_AMI
          echo "ID_OF_AMI=$ID_OF_AMI" >> "$GITHUB_OUTPUT"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}          
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  auto_deployment:
    runs-on: ubuntu-latest
    needs: [packer_build]
    env:        
          ID_OF_AMI: ${{needs.packer_build.outputs.ID_OF_AMI}}
    
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIATQUMU2VFAJ3PZG3A"
          aws-secret-access-key: "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"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: AMI id verify
        run: echo $ID_OF_AMI
      - name: check aws version
        run: "aws --version"
      - name: launchTemplate refresh to take latest ami
        run: |
          aws ec2 create-launch-template-version --no-cli-pager \
          --launch-template-data '{"ImageId":"${{env.ID_OF_AMI}}"}' \
          --source-version 1 --launch-template-id ${{vars.LAUNCH_TEMPLATE_ID}}
      - name: refresh autoscaling instance
        run: |
          aws autoscaling start-instance-refresh \
          --auto-scaling-group-name="${{vars.AUTOSCALING_GROUP_NAME}}"